### PR TITLE
Fix wrong URLs

### PR DESCRIPTION
**Pull request by seguri**

### CODE REVIEW

**Comment by RbtsEvrwhr-Riley** [comment]
URLs are wrong for the store categories, typo in the attached issue isn't even fixed. Fixing this myself. Also, the links do redirect, FYI, for any W3C compliant browser. IE6 and IE8 are not supported.

**Comment by seguri** [comment]
I did not understand your motivation, but ok if you're fixing the 3 different and broken URLs I've updated with this PR.

**Comment by RbtsEvrwhr-Riley** [comment]
I have closed this issue because the URL fixes are incorrect - they do not go to the categories in the new store. In addition, the typos lll that were linked in the email are not fixed by this PR. So I just fixed everything, emergency patched it, and it should be live now. Thanks for bringing it all to our attention! :)

**Comment by spiritplumber** [comment]
grazie mille!

**Pull request closed without merging**
